config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root "photos#index"

  resources :photos do  
    resources :comments
  end 
  
  get ':name', to: 'profiles#show', as: :profile 
  
  devise_for :users

end

app/models/adapters/only_admins.rb
class Adapters::OnlyAdmins < ActiveAdmin::AuthorizationAdapter

  def authorized?(action, subject = nil)
    user.admin?
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo

  validates :content, presence: true

  validates :rating, presence: true,
            numericality: {less_than_or_equal_to: 5 }
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
	
	has_attached_file :image, styles: { :medium => "300x" }
    validates_attachment_content_type :image, content_type: ['image/jpeg', 'image/gif', 'image/png']
end

                    

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :photos, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permited_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

  def access_denied(exception)
    flash[:danger] = exception.message
    redirect_to root_url
  end

  private
  
  def configure_permited_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation, :admin])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_photo

	def create  
	  @comment = @photo.comments.build(comment_params)
	  @comment.user_id = current_user.id

	  if @comment.save
	    flash[:success] = "You commented the hell out of that photo!"
	    redirect_to :back
	  else
	    flash[:alert] = "Check the comment form, something went horribly wrong."
	    render root_path
	  end
	end

	def destroy  
	  @comment = @photo.comments.find(params[:id])

	  @comment.destroy
	  flash[:success] = "Comment deleted :("
	  redirect_to root_path
	end  

	private

	def comment_params  
	  params.require(:comment).permit(:content, :rating)
	end

	def set_photo  
	  @photo = Photo.find(params[:photo_id])
	end  
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy, :like] 

  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def show

  end

  def edit
  	
  end

  def create
    @photo = current_user.photos.build(photo_params)

    if @photo.save
      flash[:success] = "Your photo has been created!"
      redirect_to root_path
    else
      flash[:alert] = "Your new photo couldn't be created!  Please check the form."
      render :new
    end
  end
  

  def update
    if @photo.update(photo_params)
      flash[:success] = "photo updated."
      redirect_to photos_path
    else
      flash.now[:alert] = "Update failed."
      render :edit
    end
  end

  def destroy
    @photo.destroy
    redirect_to root_path
  end

  private

  def photo_params
    params.require(:photo).permit(:image, :caption)
  end

  def set_photo  
    @photo = Photo.find(params[:id])
  end 
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
 def show  
	@photos = User.find_by(name: params[:name]).photos.order('created_at DESC')
 end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/application/navbar' %>
<hr/>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/layouts/application/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Shop', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">About</a></li>
        <li><a href="#">Contacts</a></li>
      </ul>

      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
        <p class="navbar-text">
        Hello, <%= link_to current_user.name, edit_user_registration_path(current_user), class: "navbar-link"%>
        </p>
        <ul class="navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" arai-haspopup="true" arai-expanded="false">Account <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to 'Edit profile', edit_user_registration_path(current_user)%>
              </li>
              <li>
                <a href="#">View orders</a>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to 'Sing Out', destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
        </ul>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn'%>
          <%= link_to 'Login in', new_user_session_path, class: 'btn btn-default navbar-btn'%>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/photos/_form.html.erb
<%= simple_form_for @photo, html: { class: 'form-horizontal', multipart: true } do |f| %>
	
	<div class="form-group">
  	<%= f.input :image %>
  </div>
  <div class="form-group text-center">
  	<%= f.input :caption %>
  </div>
  <div class="form-group text-center">
  	<%= f.button :submit, class: 'btn-success' %>
  </div>

<% end %>

app/views/photos/_photo.html.erb
<div class="col-md-6 col-md-offset-3">
           <%=  link_to photo.user.name, profile_path(photo.user.name) %>
            <%= link_to (image_tag photo.image.url(:medium), class:'img-responsive'), photo_path(photo) %>
              <%= photo.caption %>  

			<% if photo.user == current_user %>
              <%= link_to "delete", photo,
                                          method: :delete, 
                                          data: { confirm: "Are you sure?" } %>         
            <% end %>

</div>

                    

app/views/photos/index.html.erb
<% @photos.each do |photo| %>
  <%= render 'photos/photo', photo: photo %>
<% end %>

app/views/photos/new.html.erb
<h1>New </h1>

<%= render 'form' %>

app/views/photos/show.html.erb
<div class="photos-wrapper row">
  <div class="photo">
    <div class="photo-head">
      <div class="name">
        <%= @photo.user.name %>
      </div>
    </div>
      <div class="image center-block">
        <%=image_tag @photo.image.url(:medium) %>
      </div>
      
      <p class="caption">
        <%= @photo.caption %>
      </p>

     <p>Average score <%= Comment.average(:rating) %></p>
      <p>Add comment</p>

      <%= simple_form_for([@photo, @photo.comments.build]) do |f| %>
        <div class="field">
          <%= f.text_area :content, placeholder: "Comment..." %>
        </div>
        <%= f.input :rating, placeholder: "1-5" %>
        <%= f.submit "photo", class: "btn btn-primary" %>

      <% end %>
      
      <p>Comments</p>
  
      <% if @photo.comments %>
              <% @photo.comments.each do |comment| %>
                    <%= comment.rating %>
                    <%= comment.user %>
                    <%= comment.content %>
                    <% if comment.user == current_user %>
                      <%= link_to "delete", photo_comment_path(@photo, comment),
                                                  method: :delete, 
                                                  data: { confirm: "Are you sure?" } %>
                    <% end %>
                  </div>
              <% end %>
              </div>
      <% end %>
      
  </div>
</div>

app/views/profiles/show.html.erb
<%= link_to "create", new_photo_path %>



<% @photos.each do |photo| %>
  <%= render 'photos/photo', photo: photo %>
<% end %>